### ISSUE TITLE
Migration failure (using MySQL database)

### ISSUE THREAD

**Issue by sudeep1801** [yunojuno/django-request-token#15]
The migration file 0008_convert_token_data_to_jsonfield.py throws an error on being applied. 

Please see the error stack trace below. Does this imply that this package supports only postgres db ? 

Thanks for your time, would really appreciate your inputs on this. 

```
Running migrations:
  Applying request_token.0008_convert_token_data_to_jsonfield...DEBUG ALTER TABLE `request_token_requesttoken` MODIFY `data` jsonb NOT NULL; (params [])
DEBUG ALTER TABLE `request_token_requesttoken` MODIFY `data` jsonb NOT NULL; (params [])
DEBUG (0.000) ALTER TABLE `request_token_requesttoken` MODIFY `data` jsonb NOT NULL; args=[]
DEBUG (0.000) ALTER TABLE `request_token_requesttoken` MODIFY `data` jsonb NOT NULL; args=[]
Traceback (most recent call last):
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/Users/sudeep/PycharmProjects/Glue/lib/python3.5/site-packages/MySQLdb/connections.py", line 270, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'jsonb NOT NULL' at line 1")
```

**Comment by djm** [comment]
Hi @sudeep1801 

Yes, the package was built for our specific needs and is currently PostgreSQL only due to that.

Apologies for any false hopes, we've updated the README.

Thanks, Darian
